spring.application.name=CareerBridge

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportalDB
spring.datasource.username=postgres
spring.datasource.password=deepak@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Temporary Schema Generation for Debugging (Re-creates clean tables)
spring.jpa.hibernate.ddl-auto=create-drop

# SQL Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true